/**
 * OVERLOAD Training Categories
 * Definitions and scientifically grounded descriptions
 */

export const TRAINING_CATEGORIES = [
  {
    id: 'memory',
    name: 'Working Memory',
    shortName: 'Memory',
    tagline: 'Build sequence recall and mental buffering',
    description: 'Exercise rapid visual and sequential retention in temporary cognitive storage.',
    metricName: 'Span Capacity',
    defaultMetric: '4.8 items',
    level: 1,
    bestScore: 924,
    accuracy: '87%',
    accentColor: '#635BFF',
    icon: 'cube-outline',
    modesCount: 4,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'sequence_recall',
        name: 'Sequence Recall',
        description: 'Observe highlighted grid sequences and reproduce the exact sequential order.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'grid_memory',
        name: 'Grid Memory',
        description: 'Memorize spatial geometric matrices illuminated simultaneously.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'object_recall',
        name: 'Object Recall',
        description: 'Retain visual symbol features and identify original targets amidst distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'order_recall',
        name: 'Order Recall',
        description: 'Reconstruct the original temporal arrangement from shuffled elements.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'focus',
    name: 'Focus & Attention',
    shortName: 'Focus',
    tagline: 'Maintain attention while distractions compete',
    description: 'Enhance target acquisition speed while suppressing surrounding visual noise.',
    metricName: 'Target Precision',
    defaultMetric: '94%',
    level: 1,
    bestScore: 840,
    accuracy: '94%',
    accentColor: '#20B8A6',
    icon: 'scan-outline',
    modesCount: 2,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'target_search',
        name: 'Target Search',
        description: 'Locate and tap designated target stimuli rapidly among competing visual distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'visual_tracking',
        name: 'Visual Tracking',
        description: 'Track a designated target token as it dynamically moves and swaps positions with distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'reaction',
    name: 'Reaction Speed',
    shortName: 'Reaction',
    tagline: 'Respond to rapid changing stimuli',
    description: 'Measure and optimize raw millisecond motor response to unpredictable visual cues.',
    metricName: 'Mean Latency',
    defaultMetric: '240 ms',
    level: 1,
    bestScore: 218,
    accuracy: '96%',
    accentColor: '#D4A72C',
    icon: 'flash-outline',
    modesCount: 3,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'target_tap',
        name: 'Target Tap',
        description: 'Detect unpredictable visual onset and execute rapid motor response.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'rapid_choice',
        name: 'Rapid Choice',
        description: 'Discriminate target symbols and make instant motor decisions amidst distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'direction_reaction',
        name: 'Direction Reaction',
        description: 'Translate a visual directional cue into the correct physical response.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'processing',
    name: 'Processing Speed',
    shortName: 'Processing',
    tagline: 'Interpret and classify visual data faster',
    description: 'Train speed of information intake and accurate discrimination under pacing pressure.',
    metricName: 'Throughput',
    defaultMetric: '38 items/min',
    level: 1,
    bestScore: 710,
    accuracy: '91%',
    accentColor: '#4F8CFF',
    icon: 'speedometer-outline',
    modesCount: 4,
    status: 'upcoming',
    group: 'core',
    modes: [
      {
        id: 'rapid_comparison',
        name: 'Rapid Comparison',
        description: 'Instantly judge equivalence between dual abstract symbol arrays.',
        difficulty: 'Tier 1',
        estimatedDuration: '~90 sec',
        bestScore: 710,
        isAvailable: false,
      },
    ],
  },
  {
    id: 'decision',
    name: 'Decision Making',
    shortName: 'Decision',
    tagline: 'Choose accurately under time pressure',
    description: 'Optimize high-speed conditional choices without sacrificing accuracy.',
    metricName: 'Choice Velocity',
    defaultMetric: '91%',
    level: 1,
    bestScore: 590,
    accuracy: '89%',
    accentColor: '#8B7CF6',
    icon: 'git-branch-outline',
    modesCount: 4,
    status: 'upcoming',
    group: 'advanced',
    modes: [
      {
        id: 'fast_choice',
        name: 'Binary Rule Selection',
        description: 'Select conforming output branches based on active conditional modifiers.',
        difficulty: 'Tier 1',
        estimatedDuration: '~90 sec',
        bestScore: 590,
        isAvailable: false,
      },
    ],
  },
  {
    id: 'spatial',
    name: 'Spatial Reasoning',
    shortName: 'Spatial',
    tagline: 'Understand spatial relationships and patterns',
    description: 'Strengthen 2D and 3D mental manipulation of visual geometries.',
    metricName: 'Rotation Index',
    defaultMetric: 'Level 1',
    level: 1,
    bestScore: 480,
    accuracy: '85%',
    accentColor: '#0284C7',
    icon: 'shapes-outline',
    modesCount: 4,
    status: 'upcoming',
    group: 'advanced',
    modes: [
      {
        id: 'mental_rotation',
        name: 'Mental Rotation',
        description: 'Determine identical 3D isometric structures across arbitrary axes.',
        difficulty: 'Tier 1',
        estimatedDuration: '~2 min',
        bestScore: 480,
        isAvailable: false,
      },
    ],
  },
  {
    id: 'flexibility',
    name: 'Cognitive Flexibility',
    shortName: 'Flexibility',
    tagline: 'Adapt when sorting rules change',
    description: 'Minimize cognitive switch cost when sorting criteria change dynamically.',
    metricName: 'Switch Cost',
    defaultMetric: '180 ms',
    level: 1,
    bestScore: 520,
    accuracy: '88%',
    accentColor: '#EC4899',
    icon: 'swap-horizontal-outline',
    modesCount: 4,
    status: 'upcoming',
    group: 'advanced',
    modes: [
      {
        id: 'rule_switching',
        name: 'Dynamic Rule Shift',
        description: 'Sort objects by shape, then color, as rules invert without warning.',
        difficulty: 'Tier 1',
        estimatedDuration: '~90 sec',
        bestScore: 520,
        isAvailable: false,
      },
    ],
  },
  {
    id: 'logic',
    name: 'Logic & Problem Solving',
    shortName: 'Logic',
    tagline: 'Break complex problems into simple patterns',
    description: 'Solve deductive visual puzzles and progressive pattern relationships.',
    metricName: 'Pattern Matrix',
    defaultMetric: 'Level 1',
    level: 1,
    bestScore: 610,
    accuracy: '92%',
    accentColor: '#10B981',
    icon: 'grid-outline',
    modesCount: 4,
    status: 'upcoming',
    group: 'advanced',
    modes: [
      {
        id: 'pattern_completion',
        name: 'Matrix Reasoning',
        description: 'Complete missing matrix elements by deducing spatial transformation rules.',
        difficulty: 'Tier 1',
        estimatedDuration: '~2 min',
        bestScore: 610,
        isAvailable: false,
      },
    ],
  },
];

export default TRAINING_CATEGORIES;
