/**
 * OVERLOAD Training Categories
 * Definitions and scientifically grounded descriptions
 */

export const TRAINING_CATEGORIES = [
  {
    id: 'memory',
    name: 'Working Memory',
    shortName: 'Memory',
    tagline: 'Build sequence recall and mental buffering',
    description: 'Exercise rapid visual and sequential retention in temporary cognitive storage.',
    metricName: 'Span Capacity',
    defaultMetric: '4.8 items',
    level: 1,
    bestScore: 924,
    accuracy: '87%',
    accentColor: '#635BFF',
    icon: 'cube-outline',
    modesCount: 4,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'sequence_recall',
        name: 'Sequence Recall',
        description: 'Observe highlighted grid sequences and reproduce the exact sequential order.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'grid_memory',
        name: 'Grid Memory',
        description: 'Memorize spatial geometric matrices illuminated simultaneously.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'object_recall',
        name: 'Object Recall',
        description: 'Retain visual symbol features and identify original targets amidst distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'order_recall',
        name: 'Order Recall',
        description: 'Reconstruct the original temporal arrangement from shuffled elements.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'focus',
    name: 'Focus & Attention',
    shortName: 'Focus',
    tagline: 'Maintain attention while distractions compete',
    description: 'Enhance target acquisition speed while suppressing surrounding visual noise.',
    metricName: 'Target Precision',
    defaultMetric: '94%',
    level: 1,
    bestScore: 840,
    accuracy: '94%',
    accentColor: '#20B8A6',
    icon: 'scan-outline',
    modesCount: 2,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'target_search',
        name: 'Target Search',
        description: 'Locate and tap designated target stimuli rapidly among competing visual distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'visual_tracking',
        name: 'Visual Tracking',
        description: 'Track a designated target token as it dynamically moves and swaps positions with distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'reaction',
    name: 'Reaction Speed',
    shortName: 'Reaction',
    tagline: 'Respond to rapid changing stimuli',
    description: 'Measure and optimize raw millisecond motor response to unpredictable visual cues.',
    metricName: 'Mean Latency',
    defaultMetric: '240 ms',
    level: 1,
    bestScore: 218,
    accuracy: '96%',
    accentColor: '#D4A72C',
    icon: 'flash-outline',
    modesCount: 3,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'target_tap',
        name: 'Target Tap',
        description: 'Detect unpredictable visual onset and execute rapid motor response.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'rapid_choice',
        name: 'Rapid Choice',
        description: 'Discriminate target symbols and make instant motor decisions amidst distractors.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'direction_reaction',
        name: 'Direction Reaction',
        description: 'Translate a visual directional cue into the correct physical response.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'processing',
    name: 'Processing Speed',
    shortName: 'Processing',
    tagline: 'Interpret and classify visual data faster',
    description: 'Train speed of information intake and accurate discrimination under pacing pressure.',
    metricName: 'Throughput',
    defaultMetric: '38 items/min',
    level: 1,
    bestScore: 710,
    accuracy: '91%',
    accentColor: '#4F8CFF',
    modesCount: 3,
    status: 'ready',
    group: 'core',
    modes: [
      {
        id: 'symbol_match',
        name: 'Symbol Match',
        description: 'Compare dual symbol arrays and determine if they are identical or different.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'number_scan',
        name: 'Number Scan',
        description: 'Rapid visual search to detect and identify target numbers in a grid.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'pattern_complete',
        name: 'Pattern Complete',
        description: 'Process visual sequence rules and identify the missing terminal element.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'decision',
    name: 'Decision Making',
    shortName: 'Decision',
    tagline: 'Choose accurately under time pressure',
    description: 'Optimize high-speed conditional choices without sacrificing accuracy.',
    metricName: 'Choice Velocity',
    defaultMetric: '91%',
    level: 1,
    bestScore: 590,
    accuracy: '89%',
    modesCount: 3,
    status: 'ready',
    group: 'advanced',
    modes: [
      {
        id: 'priority_sort',
        name: 'Priority Sort',
        description: 'Evaluate competing priorities across urgency, impact, and deadlines.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'best_choice',
        name: 'Best Choice',
        description: 'Analyze multi-attribute options to identify the single optimal choice satisfying target constraints.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'rule_switch',
        name: 'Rule Switch',
        description: 'Adapt decision rules dynamically based on changing situational conditions.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'spatial',
    name: 'Spatial Reasoning',
    shortName: 'Spatial',
    tagline: 'Understand spatial relationships and patterns',
    description: 'Strengthen 2D and 3D mental manipulation of visual geometries.',
    metricName: 'Rotation Index',
    defaultMetric: 'Level 1',
    level: 1,
    bestScore: 480,
    accuracy: '85%',
    accentColor: '#0284C7',
    modesCount: 3,
    status: 'ready',
    group: 'advanced',
    modes: [
      {
        id: 'mental_rotation',
        name: 'Mental Rotation',
        description: 'Mentally rotate geometric figures and identify true transformed orientations.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'spatial_navigation',
        name: 'Spatial Navigation',
        description: 'Plan and navigate through complex environments.',
        difficulty: 'Adaptive',
        estimatedDuration: '~90 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'mirror_map',
        name: 'Mirror Map',
        description: 'Transform spatial layouts across horizontal and vertical reflection axes.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'flexibility',
    name: 'Cognitive Flexibility',
    shortName: 'Flexibility',
    tagline: 'Adapt when sorting rules change',
    description: 'Minimize cognitive switch cost when sorting criteria change dynamically.',
    metricName: 'Switch Cost',
    defaultMetric: '180 ms',
    level: 1,
    bestScore: 520,
    accuracy: '88%',
    accentColor: '#EC4899',
    modesCount: 3,
    status: 'ready',
    group: 'advanced',
    modes: [
      {
        id: 'sort_shift',
        name: 'Sort Shift',
        description: 'Rapidly switch mental sets as global sorting rules transition.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'pattern_shift',
        name: 'Pattern Shift',
        description: 'Detect mid-sequence structural rule changes and adapt predictions.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'dual_rule',
        name: 'Dual Rule',
        description: 'Select and execute the correct rule branch based on contextual cues.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
  {
    id: 'logic',
    name: 'Logic & Reasoning',
    shortName: 'Logic',
    tagline: 'Analyze relationships and deduce truths',
    description: 'Deduce unknown variables, discover sequence rules, and satisfy complex constraints.',
    metricName: 'Deduction Index',
    defaultMetric: 'Level 1',
    level: 1,
    bestScore: 610,
    accuracy: '92%',
    accentColor: '#4F46E5',
    icon: 'grid-outline',
    modesCount: 3,
    status: 'ready',
    group: 'advanced',
    modes: [
      {
        id: 'deduction_grid',
        name: 'Deduction Grid',
        description: 'Analyze clues and deduce unique entity relationships.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'sequence_logic',
        name: 'Sequence Logic',
        description: 'Discover transformation rules across mathematical sequences.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
      {
        id: 'constraint_solver',
        name: 'Constraint Solver',
        description: 'Find the only option satisfying multiple interacting conditions.',
        difficulty: 'Adaptive',
        estimatedDuration: '~60 sec',
        bestScore: null,
        isAvailable: true,
      },
    ],
  },
];

export default TRAINING_CATEGORIES;
